### PR TITLE
Plumb out more types for include/exclude lists

### PR DESCRIPTION
**Pull request by zpencer**
Expose more filtering options from the underlying japicmp library.
This is mostly adapted from this class:
https://github.com/siom79/japicmp/blob/master/japicmp/src/main/java/japicmp/config/Options.java#L177

### CODE REVIEW

**Comment by zpencer** [comment]
@melix friendly ping on this and https://github.com/melix/japicmp-gradle-plugin/pull/14

**Comment by melix** [comment]
Thanks! I'd appreciate if you could add some tests, and squash the cosmetics commits.

**Comment by zpencer** [comment]
@melix Updated with fixes, tests, and squashed

**Comment by zpencer** [comment]
@melix PTAL

**Comment by zpencer** [comment]
@melix friendly ping on this one as well

**Comment by melix** [comment]
Great, I'll prepare a release with your changes, thanks a lot!

**Comment by zpencer** [comment]
Hi @melix, any chance for a release soon? I am eager to apply this plugin into my project :)

**Comment by melix** [comment]
It's out, thanks for your contributions and sorry for the delay!

**Pull request merged**
