### PR TITLE
Upgrade to japicmp 0.7.2, add switches for HTML output and binary incompatibility report

### PR DESCRIPTION
**Pull request by swltr**
These changes upgrade japicmp to 0.7.2 and add switches for enabling HTML output and for reporting binary incompatible changes only.

### CODE REVIEW

**Comment by swltr** [comment]
@melix Do you think this could be merged?

**Comment by melix** [comment]
@swltr Thanks a lot of this PR, I'm sorry about the late merge, it totally got unnoticed from my side.

**Comment by swltr** [comment]
@melix Great, thank you! There doesn't seem to be a new version on plugins.gradle.org. Do you plan to release one?

**Comment by melix** [comment]
I do plan to release, but I'm a bit busy now. I will let you know.

**Pull request merged**
